name: Main

on:
- push
- pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '2.7.0'
        - '3.0'
        - '3.1'
        - '3.2'
        gemfile:
        - rbs1
        - rbs2
        - rbs3
    name: CI
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Test
      run: |
        bundle exec rake test
        bundle exec rake stree:check
